Project example {
  database_type: ''
  Note: ''
}

Table User {
  id int [pk, increment]
  first_name varchar
  last_name varchar
  username varchar
  email email
  password varchar
  is_activated boolean [default: false]
  activation_date datetime
  phone_number int [ref: - Phone.id]
  birth_date datetime

  // address int [ref: - Address.id]
  /* hello world */
  /*
    address int [ref: - Address.id]
  */
}

Table Phone {
  id int
  number varchar
  ext varchar

  indexes {
    id [pk, increment]
  }
}
